from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.0.0")

##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/split_fragments.smk"
include: "rules/bigwigs.smk"

# Hybrid concat ATAC branch
include: "rules/hybrid_atac.smk"

# Peak calling / differential accessibility paused for now
# include: "rules/call_peaks.smk"
# include: "rules/diff_accessibility.smk"

##### target rules #####
rule all:
    input:
        expand(
            "results/hybrid_atac/aligned_noMT/multimapper_inclusive/{sample_name}.concat.multimapper.noMT.sorted.bam",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/aligned_noMT/unique_only/{sample_name}.concat.unique.noMT.sorted.bam",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/aligned_merged/multimapper_inclusive/{sample_group}.bam",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_atac/aligned_merged/unique_only/{sample_group}.bam",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_atac/bigwigs/multimapper_inclusive/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/bigwigs/unique_only/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/bigwigs/multimapper_inclusive_merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_atac/bigwigs/unique_only_merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_atac/bigwigs_zscore/multimapper_inclusive/individual/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/bigwigs_zscore/unique_only/individual/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_atac/bigwigs_zscore/multimapper_inclusive/merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_atac/bigwigs_zscore/unique_only/merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        )
