from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.0.0")


##### setup report #####
configfile: "config/config.yaml"
# 
# 
# report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/split_fragments.smk"
include: "rules/bigwigs.smk"
include: "rules/call_peaks.smk"
include: "rules/diff_accessibility.smk"

##### target rules #####
rule all:
    input:
        expand("results/hybrid_atac/aligned/{sample}.concat.sorted.bam", sample=samples.index),
        expand("results/hybrid_atac/aligned_unique/{sample}.concat.unique.sorted.bam", sample=samples.index),

        expand("results/hybrid_atac/bigwigs/multimapper_inclusive/{sample}.bw", sample=samples.index),
        expand("results/hybrid_atac/bigwigs/unique_only/{sample}.bw", sample=samples.index),

        expand("results/hybrid_atac/bigwigs_zscore/multimapper_inclusive/individual/{sample}.bw", sample=samples.index),
        expand("results/hybrid_atac/bigwigs_zscore/unique_only/individual/{sample}.bw", sample=samples.index),

        expand("results/hybrid_atac/bigwigs_zscore/multimapper_inclusive/merged/{condition}.bw",
               condition=sorted(samples["condition"].unique())),
        expand("results/hybrid_atac/bigwigs_zscore/unique_only/merged/{condition}.bw",
               condition=sorted(samples["condition"].unique()))
