from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.0.0")

##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/split_fragments.smk"
include: "rules/bigwigs.smk"

# Hybrid concat ATAC branch
include: "rules/hybrid_atac.smk"

# Peak calling / differential accessibility paused for now
# include: "rules/call_peaks.smk"
# include: "rules/diff_accessibility.smk"

##### target rules #####
rule all:
    input:
        # individual multimapper-inclusive BAMs
        expand(
            "results/hybrid_atac/aligned/{sample_name}.concat.multimapper.sorted.bam",
            sample_name=samples.index
        ),

        # individual unique-only BAMs
        expand(
            "results/hybrid_atac/aligned_unique/{sample_name}.concat.unique.sorted.bam",
            sample_name=samples.index
        ),

        # merged multimapper-inclusive BAMs by condition
        expand(
            "results/hybrid_atac/aligned_merged/multimapper_inclusive/{sample_group}.bam",
            sample_group=sorted(samples["condition"].unique())
        ),

        # merged unique-only BAMs by condition
        expand(
            "results/hybrid_atac/aligned_merged/unique_only/{sample_group}.bam",
            sample_group=sorted(samples["condition"].unique())
        ),

        # individual multimapper-inclusive BigWigs
        expand(
            "results/hybrid_atac/bigwigs/multimapper_inclusive/{sample_name}.bw",
            sample_name=samples.index
        ),

        # individual unique-only BigWigs
        expand(
            "results/hybrid_atac/bigwigs/unique_only/{sample_name}.bw",
            sample_name=samples.index
        ),

        # merged multimapper-inclusive BigWigs by condition
        expand(
            "results/hybrid_atac/bigwigs/multimapper_inclusive_merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        ),

        # merged unique-only BigWigs by condition
        expand(
            "results/hybrid_atac/bigwigs/unique_only_merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        )
